# Cloud Build configuration for BiblioSense
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/bibliosense:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/bibliosense:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bibliosense:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bibliosense:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'bibliosense',
      '--image', 'gcr.io/$PROJECT_ID/bibliosense:$BUILD_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '1Gi',
      '--cpu', '1',
      '--timeout', '300',
      '--max-instances', '10'
    ]

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/bibliosense:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/bibliosense:latest'

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
